name: mobile_api
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: 4.6.5
  get_cli: ^1.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
